linkPrefix = ""
name = "signhash-contracts-docs"
version = "1.0.0"
description = "SignHash Contracts Documentation"
buildTime = 2018-02-08T23:35:26.839Z
target = "."
src = "node_modules/signhash-contracts/contracts/*.sol"
dir = "pages/docs"
out = "docs"
author = "Jakub Stefanski"
homepage = "https://github.com/SignHash/signhash-contracts-docs#readme"
license = "MIT"

[interaction]